---
# tasks file for ansible-vhost
#- name: copy vHost
#  template:
#    src: "{{ item.vHost | default('templates/vHost.j2') }}"
#    dest: "/etc/nginx/sites-available/{{ item.fqdn }}"
#    owner: root
#    group: root
#    mode: '0644'
#  vars:
#    NGINX_VHOST_FQDN: "{{ item.fqdn }}"
#    NGINX_REVERSE_PROXY_PORT: "{{ item.reverse_proxy_port | default('80') }}"
#    NGINX_REVERSE_PROXY_TARGET_IP: "{{ item.reverse_proxy_ip | default('127.0.0.1') }}"
#  with_items:
#    - "{{ nginx_vhosts }}"
#  when: item.state is not defined or item.state == 'present'
#  notify:
#    - restart nginx
#
#- name: activate vhost
#  file:
#    src: "/etc/nginx/sites-available/{{ item.fqdn }}"
#    dest: "/etc/nginx/sites-enabled/{{ item.fqdn }}"
#    state: link
#  with_items:
#    - "{{ nginx_vhosts }}"
#  when: item.state is not defined or item.state == 'present'
#  notify:
#    - restart nginx

- name: deactivate vhost
  file:
    dest: "/etc/nginx/sites-enabled/{{ item.fqdn }}"
    state: absent
  with_items:
    - "{{ nginx_vhosts }}"
  when: item.state is defined and item.state == 'absent'
  notify:
    - restart nginx

- name: delete vHost
  file:
    dest: "/etc/nginx/sites-available/{{ item.fqdn }}"
    owner: root
    group: root
    state: absent
    mode: '0644'
  with_items:
    - "{{ nginx_vhosts }}"
  when: item.state is defined and item.state == 'absent'
  notify:
    - restart nginx

- name: Verify Nginx config
  command: nginx -t
  changed_when: false

